import { useEffect, useState } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { supabase } from '@/lib/supabase'

/**
 * Resolves a business slug (e.g. "luxe-studio-e687fe9e") to a full business id
 * and redirects to /dashboard?business=<id>.
 *
 * The slug is stored in businesses.slug and generated by the business app.
 */
export default function JoinPage() {
  const { slug } = useParams<{ slug: string }>()
  const navigate = useNavigate()
  const [error, setError] = useState(false)

  useEffect(() => {
    if (!slug) { setError(true); return }

    supabase
      .from('businesses')
      .select('id')
      .eq('slug', slug)
      .single()
      .then(({ data, error: err }) => {
        if (err || !data) {
          setError(true)
        } else {
          navigate(`/dashboard?business=${data.id}`, { replace: true })
        }
      })
  }, [slug, navigate])

  if (error) {
    return (
      <div className="flex flex-col items-center justify-center h-full gap-2 px-6 text-center">
        <p className="text-sm font-medium text-[#0a0a0a]">Business not found</p>
        <p className="text-sm text-[#737373]">This link may be invalid or expired.</p>
      </div>
    )
  }

  // Brief loading state while resolving
  return (
    <div className="flex items-center justify-center h-full">
      <div className="size-5 rounded-full border-2 border-[#e5e5e5] border-t-[#171717] animate-spin" />
    </div>
  )
}
